// Peças apresentacionais do dashboard de leads. A composição vive no
// app/leads/LeadsClient.tsx (dentro do AppShell), como no dashboard do discador.
// PeriodPicker mudou para @/components/blueline/PeriodPicker (compartilhado com a discadora).
export { LeadKpiRow } from './components/LeadKpiRow'
export { Funnel } from './components/Funnel'
export { PhaseDistribution } from './components/PhaseDistribution'
export { ResponsibleBreakdown } from './components/ResponsibleBreakdown'
export { DeadReasonsDonut } from './components/DeadReasonsDonut'
export { DeathByAttempt } from './components/DeathByAttempt'
export { LeadsTable } from './components/LeadsTable'
export { AgentRanking } from './components/AgentRanking'
export { DuplicateAlert } from './components/DuplicateAlert'
export { ForgottenLeads } from './components/ForgottenLeads'
export { ChannelBreakdown } from './components/ChannelBreakdown'
export { OrphanLeads } from './components/OrphanLeads'
export { EvolutionChart } from './components/EvolutionChart'
export { TrendChart } from './components/TrendChart'
export { PerformancePanel } from './components/PerformancePanel'
export { StepDwellTime } from './components/StepDwellTime'
export { StepConversion } from './components/StepConversion'
export { AlertsPanel, type AlertItem } from './components/AlertsPanel'
export { LeadsTabNav, type LeadTab } from './components/LeadsTabNav'
export { TabPlaceholder } from './components/TabPlaceholder'
export { PRODUCTIVE_PHASES, DEAD_PHASES, WON_ORDER } from './content/phases'
